- name: Install packages
  apt:
    pkg: ['apache2', 'libapache2-mod-php', 'git']
    state: present
    update_cache: true
  tags:
    - apache

- name: Push virtual host conf
  copy:
    src: files/awesome-app
    dest: /etc/apache2/sites-available/awesome-app.conf
    mode: 0640
  tags:
    - apache

- name: Activates virtualhost
  command: a2ensite awesome-app
  tags:
    - apache

- name: Check config is valid
  command: apache2ctl configtest
  register: result
  ignore_errors: true
  tags:
    - apache

- name: Rolling back - Restoring old default virtualhost
  command: a2ensite 000-default
  when: result is failed
  tags:
    - apache

- name: Rolling back - Ending playbook
  fail:
    msg: "Config error. Rolling back to old configuration"
  when: result is failed
  tags:
    - apache

- name: Deploy app
  git:
    repo: https://github.com/leucos/ansible-tuto-demosite.git
    dest: /var/www/awesome-app
  tags: 
    - deploy
    - apache

- name: Deactivates the default virtualhost
  command: a2dissite 000-default
  tags:
    - apache

- name: Deactivates default ssl virtualhost
  command: a2dissite default-ssl
  notify: restart apache
  tags:
    - apache